<h2 class="mt-5 fw-semibold"><?= htmlspecialchars($title) ?></h2>
<p class="text-muted">Informe os dados do banheiro </p>

<div class="form-background">
    <form id="formCadastroBanheiro" method="POST"
        action="<?= route('admin.buildings.bathrooms.create', ['building_id' => $building->id]) ?>"
        enctype="multipart/form-data">

        <!-- Prédio fixo -->
        <div class="mb-3">
            <label class="form-label fw-semibold">Nome do prédio</label>
            <p class="form-control-plaintext"><?= htmlspecialchars($building->name) ?></p>
            <input type="hidden" name="bathroom[building_id]" value="<?= $building->id ?>">
        </div>

        <!-- Andar -->
        <div class="mb-3">
            <label class="form-label fw-semibold">Andar</label>
            <select class="form-select field-floor" id="id_floor" name="bathroom[floor]" required>
                <?php for ($i = 0; $i < $building->n_floors; $i++): ?>
                    <option value="<?= $i ?>"><?= $i + 1 ?>º andar</option>
                <?php endfor; ?>
            </select>
        </div>

        <?php foreach ($types as $type): ?>
            <div class="mb-3">
                <label class="form-label fw-semibold"><?= $type->name ?></label>
                <select class="form-select" name="items[<?= $type->id ?>]" required>
                    <?php for ($i = 0; $i <= 50; $i++): ?>
                        <option value="<?= $i ?>">
                            <?= $i ?>
                        </option>
                    <?php endfor; ?>
                </select>
            </div>
        <?php endforeach; ?>

        <!-- Botões -->
        <div class="d-flex justify-content-between mt-4">
            <!-- Botão Voltar para a lista de banheiros do prédio -->
            <a href="<?= route('admin.buildings.bathrooms.index', ['building_id' => $building->id]) ?>"
                class="btn btn-voltar rounded-pill px-4 link-comeback">Voltar</a>

            <button type="submit" class="btn btn-primary rounded-pill px-4 d-flex align-items-center gap-2 link-submit">
                <i class="bi bi-building-add"></i>
                Salvar Banheiro
            </button>
        </div>

    </form>
</div>
