<h2 class="mt-4 fw-semibold">Cadastrar Banheiros</h2>
<p class="text-muted">Informe os dados dos banheiros do predio</p>

<div class="form-background">
    <form id="formCadastroBanheiro" method="POST">
        <div class="mb-3">
            <label class="form-label fw-semibold">Número de Banheiros por andar</label>
            <select class="form-select" id="id_n_floors" name="building[n_floors]" required>
                <?php for ($i = 1; $i <= 10; $i++): ?>
                    <option value="<?= $i ?>"><?= $i ?> banheiro<?= $i > 1 ? 'es' : '' ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label fw-semibold">Numero de torneiras por Banheiro</label>
            <select class="form-select" id="id_n_floors" name="building[n_floors]" required>
                <?php for ($i = 1; $i <= 30; $i++): ?>
                    <option value="<?= $i ?>"><?= $i ?> torneiras<?= $i > 1 ? 'es' : '' ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label fw-semibold">Numero de vasos por Banheiro</label>
            <select class="form-select" id="id_n_floors" name="building[n_floors]" required>
                <?php for ($i = 1; $i <= 30; $i++): ?>
                    <option value="<?= $i ?>"><?= $i ?> vasos<?= $i > 1 ? 'es' : '' ?></option>
                <?php endfor; ?>
            </select>
        </div>

        <div class="d-flex justify-content-between mt-4">
            <a href="<?= route('admin.buildings.index') ?>" class="btn btn-voltar rounded-pill px-4">Voltar</a>
            <button type="submit" class="btn btn-primary rounded-pill px-4 d-flex align-items-center gap-2">
                <i class="bi bi-building-add"></i>
                Salvar Prédio
            </button>
        </div>

    </form>
</div>

</div>