<h2 class="mt-5 fw-semibold">Detalhes do Banheiro</h2>
<p class="text-muted">Visualize as informações do Banheiro cadastrado.</p>

<div class="row mt-4">
    <div class="col-md-6">
        <div class="card shadow-sm border border-primary border-2 p-4">
            <h4 class="fw-semibold mb-3"> Predio <?= htmlspecialchars($bathroom->building_id) ?></h4>
            <div class="mb-2">
                <span class="fw-semibold text-secondary">Andar</span>
                <span><?= $bathroom->floor ?></span>
            </div>
            <div class="mb2">
                <img class="bathroom_image" src="/assets/uploads/<?= $bathroom->image_url?>">
            </div>

            <div class="d-flex justify-content-between mt-4">
                <a href="<?= route('admin.buildings.index') ?>" class="btn btn-voltar rounded-pill px-4 link-comeback">
                    Voltar
                </a>

                <a href="<?= route('admin.bathrooms.edit', ['id' => $bathroom->id]) ?>" class="btn btn-primary fw-semibold px-4 rounded-pill link-edit">
                    Editar
                </a>

            </div>
        </div>
    </div>
</div>
