<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand text-primary fw-bold" href="#">
            <img src="/assets/images/defaults/logoMapasODS.png" alt="Avatar do Usuário" class="rounded-circle">
        </a>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav align-items-lg-center">
                <li class="nav-item me-3">
                    <a class="nav-link" href="#">Dashboard</a>
                </li>

                <li class="nav-item me-3">
                    <a class="nav-link" href="#">Consultar Predio</a>
                </li>

                <li class="nav-item me-3">
                    <a class="nav-link" href="#">Relatorios</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="/assets/images/defaults/avatarUser.png" alt="Avatar do Usuário" class="rounded-circle avatar" style="width: 40px; height: 40px; object-fit: cover;">
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Sair</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>