<h2 class="mt-5 fw-semibold"><?= htmlspecialchars($title) ?></h2>
<p class="text-muted">Informe os dados dos itens</p>

<div class="form-background">
    <form id="formCadastroItem" method="POST"
        action="<?= route('admin.buildings.bathrooms.items.update', [
                    'building_id' => $building->id,
                    'bathroom_id' => $bathroom->id
            ]) ?>">

        <input type="hidden" name="_method" value="PUT">

        <!-- Item: Torneiras -->
        <div class="mb-3">
            <label class="form-label fw-semibold">Torneiras</label>
            <select class="form-select" name="items[taps]" required>
                <?php for ($i = 0; $i <= 50; $i++): ?>
                    <option value="<?= $i ?>"
                        <?= $taps->quantity == $i ? 'selected' : '' ?>>
                        <?= $i ?>
                    </option>
                <?php endfor; ?>
            </select>
        </div>

        <!-- Item: Vasos -->
        <div class="mb-3">
            <label class="form-label fw-semibold">Vasos</label>
            <select class="form-select" name="items[toilets]" required>
                <?php for ($i = 0; $i <= 50; $i++): ?>
                    <option value="<?= $i ?>"
                        <?= $toilets->quantity == $i ? 'selected' : '' ?>>
                        <?= $i ?>
                    </option>
                <?php endfor; ?>
            </select>
        </div>

        <div class="d-flex justify-content-between mt-4">
            <a href="<?= route('admin.buildings.bathrooms.items.index', [
                            'building_id' => $building->id,
                            'bathroom_id' => $bathroom->id
                        ]) ?>"
                class="btn btn-voltar rounded-pill px-4 link-comeback">Voltar</a>

            <button type="submit" class="btn btn-primary rounded-pill px-4 d-flex align-items-center gap-2 link-submit">
                <i class="bi bi-items-add"></i>
                Salvar Item
            </button>
        </div>

    </form>
</div>
