<h2 class="mt-5 fw-semibold"><?= $title ?></h2>
<p class="text-muted">Itens cadastrados neste banheiro</p>

<?php
$items = $items ?? [];
?>

<div>

    <table id="tableBuildingsDashboard" class="table align-middle text-center">
        <thead class="table-primary">
            <tr>
                <th>QTD</th>
                <th>Tipo</th>
                <th>Consumo médio em litros por minuto / acionamento</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <?php if (!empty($items)): ?>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td class="text-secondary">
                            <?= htmlspecialchars($item->quantity) ?>
                        </td>

                        <td class="text-secondary">
                        <a href="<?= route('admin.bathroom_item_types.show', [
                            'id' => $item->type()->get()->id
                        ])?>">
                                <?= htmlspecialchars($item->type()->get()->name ?? 'Sem tipo') ?>
                            </a>
                        </td>

                        <td class="text-secondary">
                            <?= htmlspecialchars($item->type()->get()->vendor_consumption_expenditure ?? 'Sem modelo') ?>
                        </td>

                        <td>
                            <div class="d-flex justify-content-center gap-2">
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="text-muted">Nenhum item cadastrado.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>

<?php $paginator->renderPagesNavigation(); ?>

<div class="d-flex justify-content-between mt-4 mb-5">
    <a href="<?= route('admin.buildings.bathrooms.index', ['building_id' => $bathroom->building_id]) ?>" class="btn btn-voltar rounded-pill px-4 link-comeback">Voltar</a>
</div>
</div>
