<div class="mb-0">
    <?php include __DIR__ . '/../components/navbar.admin.phtml'; ?>
</div>

<div class="sidebar">
    <?php include __DIR__ . '/../components/sidenav.admin.phtml'; ?>
</div>

<div id="main-content">
    <div class="container-fluid pt-5 mt-4 p-0 px-5">
        <div class="row">
            <div class="col-12">
                <h2 class="mt-4 fw-semibold">Cadastrar Nova Estrutura.</h2>
                <p class="text-muted">Informe os dados da nova estrutura</p>

                <div class="form-background">
                    <form id="formCadastroPredio">
                        <div class="mb-3">
                            <label for="nomePredio" class="form-label fw-semibold">Nome do Prédio</label>
                            <input
                                type="text"
                                class="form-control"
                                id="nomePredio"
                                name="nomePredio"
                                placeholder="Digite o nome do prédio"
                                required>
                        </div>

                        <div class="mb-4">
                            <label for="areaTotal" class="form-label fw-semibold">Área Total Construída (m²)</label>
                            <input
                                type="text"
                                class="form-control"
                                id="areaTotal"
                                name="areaTotal"
                                placeholder="Informe a área total">
                        </div>

                        <div class="d-flex justify-content-between mt-5">
                            <a href="/admin/dashboard.admin" class="btn btn-voltar rounded-pill px-4">Voltar</a>
                            <button type="submit" class="btn btn-primary rounded-pill px-4 d-flex align-items-center gap-2">
                                <i class="bi bi-building-add"></i>
                                Cadastrar Andares
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>