<div>
    <h2>Dashboard Cliente</h2>


    <div class="d-flex flex-column align-items-center justify-content-center text-center py-5" style="min-height: 70vh;">
        <div class="mb-4">
            <h1 class="display-1 fw-bold text-danger">503</h1>
            <h2 class="fw-semibold">Serviço Indisponível</h2>
            <p class="text-muted mt-3">
                O servidor está temporariamente fora do ar para manutenção ou sobrecarga. <br>
                Por favor, tente novamente mais tarde.
            </p>
        </div>
     
    </div>




</div>