    <div class="d-flex align-items-center justify-content-center min-vh-100">
        <div class="card login-card shadow-lg w-100">
            <div class="row g-0">

                <!-- Lado Esquerdo -->
                <div class="col-md-6 login-left d-flex flex-column align-items-center justify-content-center p-4">
                    <img src="/assets/images/defaults/logoODS.jpg" alt="Logo Mapas ODS" class="mb-4">
                    <h1 class="fw-bold">Mapas ODS</h1>
                    <p class="text-center mt-3">
                        Análise de dados de consumo de água para um futuro sustentável
                    </p>
                </div>

                <!-- Lado Direito -->
                <div class="col-md-6 d-flex flex-column justify-content-center p-5">
                    <h2 class="mb-4 text-center">Login</h2>
                    <form method="POST" action="<?= route('auth.login') ?>" id="login_form">

                        <!-- Usuário -->
                        <div class="mb-3">
                            <label for="usuario" class="form-label">Usuário</label>
                            <div class="input-group">
                                <span class="input-group-text">
                                    <i class="bi bi-person"></i>
                                </span>
                                <input type="text" name="usuario" id="usuario" class="form-control" placeholder="Digite seu usuário" required>
                            </div>
                        </div>

                        <!-- Senha -->
                        <div class="mb-4">
                            <label for="senha" class="form-label">Senha</label>
                            <div class="input-group">
                                <span class="input-group-text">
                                    <i class="bi bi-lock"></i>
                                </span>
                                <input type="password" name="senha" id="senha" class="form-control" placeholder="Digite sua senha" required>
                            </div>
                        </div>

                        <!-- Botão -->
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-box-arrow-in-right me-2"></i> Entrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
 <script src="/assets/js/auth.js"/>
