<h2 class="mt-5 fw-semibold"><?= htmlspecialchars($title) ?></h2>
<p class="text-muted">Informe os dados do novo item </p>

<div class="form-background">
    <form id="formCadastroBanheiro" method="POST"
        action="<?= route('admin.bathroom_item_types.create') ?>"
        enctype="multipart/form-data">


        <!-- Nome -->
        <div class="mb-3">
            <label class="form-label fw-semibold">Nome do item</label>
            <input type="text" class="form-select field-floor" id="id_floor" name="type[name]" required />
        </div>

        <!-- Consumo medio -->
        <div class="mb-3">
            <label class="form-label fw-semibold">Consumo mestro em litros</label>
            <input type="text" class="form-select" name="type[vendor_consumption_expenditure]" required />
        </div>


        <!-- Botões -->
        <div class="d-flex justify-content-between mt-4">
            <!-- Botão Voltar para a lista de typos de items do prédio -->
            <a href="<?= route('admin.bathroom_item_types.index') ?>"
                class="btn btn-voltar rounded-pill px-4 link-comeback">Voltar</a>

            <button type="submit" class="btn btn-primary rounded-pill px-4 d-flex align-items-center gap-2 link-submit">
                <i class="bi bi-building-add"></i>
                Salvar Typo De Banheiro
            </button>
        </div>

    </form>
</div>