<h2 class="mt-5 fw-semibold"><?= htmlspecialchars($title) ?></h2>
<p class="text-muted">Informações dos itens cadastrados.</p>

<div class="row mt-4 mb-5">
    <div class="col-md-12">
        <div class="card shadow-sm border border-primary border-2 p-5">

            <!-- Informações Gerais -->
            <h4 class="fw-semibold mb-3">Informações Gerais</h4>

            <div class="mb-3">
                <p class="mb-1">
                    <strong>Nome do item:</strong> <?= htmlspecialchars($type->name) ?>
                </p>

                <p class="mb-1">
                    <strong>Consumo médio em litros por acionamento:</strong>
                    <?= $type->vendor_consumption_expenditure ?>L
                </p>

                <p class="mb-0">
                    <strong>Total de item cadastrados no banheiro:</strong>
                    <?= array_sum(array_map(
                        fn($i) => ($i->quantity),
                        $type->items()->get()
                    )) ?>
                </p>
            </div>

            <hr class="my-4" style="border: 0; border-top: 3px solid #d0d0d0; opacity: 1;">

            <!-- Disponibilidade -->
            <h4 class="mt-3 mb-3 fw-semibold">Outros lugares que usam o mesmo item</h4>

            <?php if (isset($bathrooms) && !empty($bathrooms)): ?>
                <ul class="mb-0">
                    <?php foreach ($bathrooms as $bathroom): ?>
                        <li class="mb-1">
                            <?= $bathroom->building()->get()->name ?> -
                            <?= $bathroom->floor + 1 ?> º andar

                            <a
                                href="<?= route('admin.buildings.bathrooms.show', [
                                            'id' => $bathroom->id
                                        ]) ?>"
                                class="ms-2 text-primary fw-semibold">
                                Mais detalhes
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <p class="text-muted mb-0">Este item não está associado a nenhum banheiro.</p>
            <?php endif; ?>

            <!-- Navegação atual-->
            <div class="d-flex justify-content-between mt-4">
                <a
                    href="<?= route('admin.buildings.bathrooms.items.index', [
                                'building_id' => $bathroom->building_id,
                                'bathroom_id' => $bathroom->id
                            ]) ?>"
                    class="btn btn-voltar rounded-pill px-4 link-comeback">
                    Voltar
                </a>
            </div>

            <!-- Navegação Função para quando cliente solicitar adicionar itens,
             momento como não a demanda botão fica desativado mas já funcional
             ver CRUD de itensTypes
            <div class="d-flex justify-content-between mt-4">
                <a
                    href="<?= route('admin.bathroom_item_types.index') ?>"
                    class="btn btn-voltar rounded-pill px-4 link-comeback">
                    Voltar
                </a>
            </div>  -->

        </div>
    </div>
</div>