<h2 class="mt-5 fw-semibold"><?= htmlspecialchars($title) ?></h2>
<p class="text-muted">Visualize as informações dos tipos de itens.</p>

<div class="row mt-4 mb-5">
    <div class="col-md-12">
        <div class="card shadow-sm border border-primary border-2 p-5">

            <!-- Informações Gerais -->
            <h4 class="fw-semibold mb-3"><?= $type->name?></h4>



            <hr class="my-4" style="border: 0; border-top: 3px solid #d0d0d0; opacity: 1;">
            <p>
                Consumo medio:
                <?= $type->vendor_consumption_expenditure?>L
            </p>

            <p>
                Total de itens:
                <?= array_sum(array_map(
                    fn ($i) => ($i->quantity),
                    $type->items()->get()
                )) ?>
            </p>


            <!-- Navegação -->
            <div class="d-flex justify-content-between mt-4">
                <a href="<?= route('admin.bathroom_item_types.index') ?>"
                    class="btn btn-voltar rounded-pill px-4 link-comeback">
                    Voltar
                </a>

            </div>

        </div>
    </div>
</div>
<script src="/assets/js/admin/bathroom/show.js"></script>
