<div class="mb-0">
    <?php include __DIR__ . '/../components/navbar.admin.phtml'; ?>
</div>

<div class="sidebar">
    <?php include __DIR__ . '/../components/sidenav.admin.phtml'; ?>
</div>

<div id="main-content">
    <div class="container-fluid pt-5 mt-4 p-0 px-5">
        <h2 class="mt-4 fw-semibold">Lista de Prédios</h2>
        <div class="table-responsive mt-4">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nome do Prédio</th>
                        <th>Número de Andares</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($predios as $predio): ?>
                        <tr>
                            <td><?= htmlspecialchars($predio['name']) ?></td>
                            <td><?= htmlspecialchars($predio['n_floors']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>