<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card text-white bg-primary mb-3 shadow-sm">
                <div class="card-body d-flex flex-column align-items-center justify-content-center">
                    <h5 class="card-title">Total de Prédios</h5>
                    <p class="card-text display-4"><?= $totalPredios ?></p>
                    <i class="bi bi-building" style="font-size: 2rem;"></i>
                </div>
            </div>
        </div>
    </div>
</div>


<div>
    <a href="<?= route('admin.buildings.index') ?>">Ver todos</a>
</div>