<h2 class="mt-5 fw-semibold">Detalhes do Prédio</h2>
<p class="text-muted">Visualize as informações do prédio cadastrado.</p>

<div class="row mt-4">
    <div class="col-md-6">
        <div class="card shadow-sm border border-primary border-2 p-4">
            <h4 class="fw-semibold mb-3"><?= htmlspecialchars($building->name) ?></h4>
            <div class="mb-2">
                <span class="fw-semibold text-secondary">Quantidade de Andares:</span>
                <span><?= $building->n_floors ?></span>
                <br>
                <span class="fw-semibold text-secondary">Total de Banheiros:</span>
                <span><?= $totalBathrooms ?></span>
                <br>
            </div>

            <div class="d-flex justify-content-between mt-4">
                <a href="<?= route('admin.buildings.index') ?>" class="btn btn-voltar rounded-pill px-4 link-comeback">
                    Voltar
                </a>
                <a href="<?= route('admin.buildings.edit', ['id' => $building->id]) ?>" class="btn btn-primary fw-semibold px-4 rounded-pill link-edit">
                    Editar
                </a>
            </div>
        </div>
    </div>
</div>